---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - api
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
